# ResumeUpdater Workflow

name: ResumeUpdater

on:
  schedule:
    - cron: '15 3 * * *'  # This is run at 9:15 AM IST

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: IST Time
        run: TZ=Asia/Kolkata date
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update resume
        run: echo 'Updating resume...'; # Add your update commands here
